version: '3.8'

services:
  site:
    image: ${DOCKER_IMAGE}
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d:ro # nginx conf
      - ./certbot/conf/:/etc/nginx/ssl/:ro # ssl cert
      - ./nginx/log/:/var/log/nginx:rw # nginx logs
    env_file:
      - ./.env
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/:rw
