baseURL = "https://127.0.0.1/"
languageCode = "en-us"
title = "Example Lekh Site"
theme = "lekh"

[params]
Name = "Vjekoslav Drakšić"
About = "Testing stuff"
Email = "vjekoslav.draksic@gmail.com"
Resume = "" # Add the filename with file extension.
PostLimit = 4 # Sets the number of posts to display on the front page
GoatCounterCode = ""

[[params.profiles]]
name = "GitHub"
url = "https://github.com/Vdraksic"

[[params.profiles]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/vjekoslav-drak%C5%A1i%C4%87-74851a20a/"