name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'dockerfile'
      - 'site/**'  
  workflow_dispatch:
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-south-1

    - name: Build and push Docker image
      env:
        ECR_REPOSITORY: dpecr
      run: |
        docker build -t $ECR_REPOSITORY:${{ github.sha }} .
        docker tag $ECR_REPOSITORY:${{ github.sha }} $ECR_REPOSITORY:latest
        docker push $ECR_REPOSITORY:${{ github.sha }}
        docker push $ECR_REPOSITORY:latest

    - name: Slack notification on success or failure 
      uses: ravsamhq/notify-slack-action@v2
      with:
        status: ${{ job.status }}
      env: 
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
